CREATE DATABASE CPN_DB;

CREATE TABLE TPATIENTE (
    CODEPATIENTE INT NOT NULL AUTO_INCREMENT,
    NOM VARCHAR(25),
    POSTNOM VARCHAR(25),
    PRENOM VARCHAR(25),
    DATENAISS DATE,
    PARTENAIRE VARCHAR(25),
    ETATCIVIL VARCHAR(15),
    ADRESSE VARCHAR(25),
    OCCUPATION VARCHAR(25),
    CONSTRAINT PK_PA PRIMARY KEY(CODEPATIENTE),
    AUTEUR VARCHAR(50),
    DDATE DATE
);

CREATE TABLE TANTECEDENT (
    CODEANTECEDENT INT NOT NULL AUTO_INCREMENT,
    REFPATIENTE INT,
    HTARTERIELLE VARCHAR(15),
    DBT VARCHAR(15),
    CARDIOPAT VARCHAR(15),
    ISTVIH VARCHAR(15),
    AUTRES VARCHAR(25),
    CESRIENE VARCHAR(15),
    CERCLAGE VARCHAR(15),
    FIBROME VARCHAR(15),
    FRACTBASSIN VARCHAR(15),
    GPU VARCHAR(15),
    DDR DATE,
    PARITE INT,
    GROSSESSE INT,
    ENFANTVIE INT,
    AVORTEMENT INT,
    AVORTFIRSTTRIM INT,
    TRIMPART15 VARCHAR(15),
    TRIMPART30PLUS VARCHAR(15),
    LASTACCOUCH DATE,
    INTERVAL2ANS VARCHAR(15),
    DYSTOCIE VARCHAR(25),
    EUDOCIE VARCHAR(25),
    BIGPOIDS DECIMAL,
    POIDSSUP4 DECIMAL,
    LASTBORNPREMA INT,
    POSTMAT VARCHAR(25),
    MORTNE VARCHAR(25),
    MORTAVSEPT VARCHAR(25),
    COMPSTERILITE VARCHAR(25),
    COMPOSTPAT VARCHAR(15),
    COMPPOSTPATOUI VARCHAR(25),
    CONSTRAINT PK_ANT PRIMARY KEY (CODEANTECEDENT),
    AUTEUR VARCHAR(50),
    DDATE DATE
);

CREATE TABLE TEVOLUTION (
    CODEEVOLUTION INT NOT NULL AUTO_INCREMENT,
    REFPATIENTE INT,
    DDR DATE,
    CONJONCTIVITE VARCHAR(25),
    DATECONSULT DATE,
    HTUTERINE DOUBLE(3, 2),
    MVTFEOTAL VARCHAR(25),
    BCF INT,
    PRESENTATION VARCHAR(25),
    PERTLIQUI VARCHAR(25),
    EODEM VARCHAR(25),
    ALBUMIN VARCHAR(25),
    GLYCEMIE VARCHAR(25),
    TARTERIELLE VARCHAR(25),
    CONTRACTION VARCHAR(25),
    BASPROMO VARCHAR(25),
    POIDS DECIMAL,
    TAILLE DECIMAL,
    TAILLESUP VARCHAR(25),
    CONSTRAINT PK_EVO PRIMARY KEY(CODEEVOLUTION),
    CONSTRAINT FK_PATIE FOREIGN KEY (REFPATIENTE) REFERENCES TPATIENTE(CODEPATIENTE),
    AUTEUR VARCHAR(50),
    DDATE DATE
);

CREATE TABLE TVACCIN (
    CODEVACCIN INT NOT NULL AUTO_INCREMENT,
    DESIGNATION VARCHAR(25),
    CONSTRAINT PK_VACCIN PRIMARY KEY (CODEVACCIN),
    AUTEUR VARCHAR(50),
    DDATE DATE
);

CREATE TABLE TVACCINATION (
    CODEVACCINATION INT NOT NULL AUTO_INCREMENT,
    REFPATIENTE INT,
    REFVACCIN INT,
    DATEVACCIN DATE,
    CONSTRAINT PK_VACCI PRIMARY KEY(CODEVACCINATION),
    AUTEUR VARCHAR(50),
    DDATE DATE
);

CREATE TABLE TTRAITEMENT (
    CODETRAITEMENT INT NOT NULL AUTO_INCREMENT,
    REFPATIENTE INT,
    MILDA VARCHAR(25),
    SIMILDA DATE,
    SPFER VARCHAR(25),
    VERMIFUGE VARCHAR(25),
    CONSTRAINT PK_TRAIT PRIMARY KEY(CODETRAITEMENT),
    AUTEUR VARCHAR(50),
    DDATE DATE
);

CREATE TABLE TLASTCONSULTATION (
    CODELASTCONSULT INT NOT NULL AUTO_INCREMENT,
    REFPATIENTE INT,
    CONJ VARCHAR(25),
    HB7ET50 VARCHAR(25),
    HTUTERINE DOUBLE(3, 2),
    PLUSDE36 VARCHAR(25),
    BTF VARCHAR(25),
    SIBTF VARCHAR(25),
    PRESENTATION VARCHAR(25),
    OEDEM VARCHAR(25),
    ALBUMINE VARCHAR(25),
    TA DOUBLE(3, 2),
    TAMOTIF VARCHAR(25),
    PERTLIQUI VARCHAR(25),
    AUTREPRECISION VARCHAR(25),
    CONTRACTION VARCHAR(25),
    CONSTRAINT PK_CONSL PRIMARY KEY (CODELASTCONSULT),
    AUTEUR VARCHAR(50),
    DDATE DATE
);

CREATE TABLE TDECISION (
    CODEDECISION INT NOT NULL AUTO_INCREMENT,
    REFCONSULATION INT,
    CPNNORMAL VARCHAR(25),
    RDVMAT DATE,
    RAISON VARCHAR(255),
    CONSTRAINT PK_DECI PRIMARY KEY(CODEDECISION),
    AUTEUR VARCHAR(50),
    DDATE DATE
);

CREATE TABLE TMATERNITE (
    CODEMAT INT NOT NULL AUTO_INCREMENT,
    REFPATIENTE INT,
    EXAPHYSIQUE VARCHAR(50),
    EXAPARACLINIQUE VARCHAR(50),
    AUTROBS VARCHAR(255),
    CONCLUSION VARCHAR(255),
    DECISION VARCHAR(255),
    CONSTRAINT PK_MAT PRIMARY KEY(CODEMAT),
    AUTEUR VARCHAR(50),
    DDATE DATE
);

CREATE TABLE TEXAMEN (
    CODEEXAMEN INT NOT NULL AUTO_INCREMENT,
    DESIGNATION VARCHAR(25),
    CONSTRAINT PK_EXAMEN PRIMARY KEY(CODEEXAMEN),
    AUTEUR VARCHAR(50),
    DDATE DATE
);

CREATE TABLE TEXAPASSE (
    CODEEXAMPASS INT NOT NULL AUTO_INCREMENT,
    REFEXAM INT,
    REFPATIENTE INT,
    RESUTLTAT VARCHAR(25),
    TRAITEMENT VARCHAR(25),
    CONSTRAINT PK_CODEEXAMPASS PRIMARY KEY(CODEEXAMPASS),
    AUTEUR VARCHAR(50),
    DDATE DATE
);

CREATE TABLE TFONCTION (
    CODEFONCTION INT NOT NULL AUTO_INCREMENT,
    DESIGNATION VARCHAR(25),
    AUTEUR VARCHAR(50),
    DDATE DATE,
    CONSTRAINT PK_USER PRIMARY KEY (CODEFONCTION)
);

CREATE TABLE TUTILISATEUR (
    CODEUTILISATEUR INT NOT NULL AUTO_INCREMENT,
    NOM VARCHAR(25),
    POSTNOM VARCHAR(25),
    PRENOM VARCHAR(25),
    ADRESSE VARCHAR(25),
    REFFONCTION INT,
    DDATE DATE,
    AUTEUR VARCHAR(50),
    CONSTRAINT PK_USER PRIMARY KEY (CODEUTILISATEUR)
);

CREATE TABLE TCOMPTE (
    CODECOMPTE INT NOT NULL AUTO_INCREMENT,
    REFUTILISATEUR INT,
    USERNAME VARCHAR(25),
    MOTDEPASS VARCHAR(25),
    DDATE DATE,
    CONSTRAINT PK_COMPTE PRIMARY KEY(CODECOMPTE)
);

CREATE TABLE PLANNING (
    CODEPLANNING INT NOT NULL AUTO_INCREMENT,
    REFPATIENTE INT,
    DATERDV DATE,
    DDATE DATE,
    AUTEUR VARCHAR(50),
    CONSTRAINT PK_PLANNING PRIMARY KEY(CODEPLANNING)
);

CREATE TABLE COMPANY (
    CODECOMPANY INT NOT NULL AUTO_INCREMENT,
    COUNTRY VARCHAR(50),
    MINISTRY VARCHAR(50),
    PROVINCE VARCHAR(50),
    DISTRICT VARCHAR(50),
    ASFORMATION VARCHAR(50),
    AV VARCHAR(50),
    QUARTIER VARCHAR(50),
    COMMUNE VARCHAR(50),
    TEL VARCHAR(50),
    EMAIL VARCHAR(50),
    LOGO VARCHAR(100),
    ZONE VARCHAR(50),
    CONSTRAINT PK_COMPANY PRIMARY KEY(CODECOMPANY)
);

INSERT INTO TFONCTION (
    DESIGNATION
)VALUES (
    'Administrateur'
);

INSERT INTO `TUTILISATEUR` (
    `CODEUTILISATEUR`,
    `NOM`,
    `POSTNOM`,
    `PRENOM`,
    `ADRESSE`,
    `REFFONCTION`,
    `DDATE`,
    `AUTEUR`
) VALUES (
    NULL,
    'Mumbere',
    'Tsongo',
    'Nathanaël',
    'Goma/Virunga',
    '1',
    CURDATE(),
    'Tsongo Nathanaël'
);

INSERT INTO `TFONCTION` (
    `CODEFONCTION`,
    `DESIGNATION`,
    `AUTEUR`,
    `DDATE`
) VALUES (
    NULL,
    'Administrateur',
    'Tsongo Nathanael',
    CURDATE()
);

INSERT INTO `COMPANY` (
    `CODECOMPANY`,
    `COUNTRY`,
    `MINISTRY`,
    `PROVINCE`,
    `DISTRICT`,
    `ASFORMATION`,
    `AV`,
    `QUARTIER`,
    `COMMUNE`,
    `TEL`,
    `EMAIL`,
    `LOGO`,
    `ZONE`
) VALUES (
    NULL,
    'RDC',
    'SANTE',
    'NORD-KIVU',
    'GOMA',
    'HGL',
    'Nyamulagira',
    'Murara',
    'Karisimbi',
    '+243995247814',
    'hglgoma@gmail.com',
    'null',
    'Karisimbi'
);

INSERT INTO `TCOMPTE`(
    `REFUTILISATEUR`,
    `USERNAME`,
    `MOTDEPASS`,
    `DDATE`
) VALUES (
    1,
    'Admin',
    'Admin',
    CURRENT_DATE
)